config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # Associations
  belongs_to :movie
  belongs_to :list

  # Validations
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  # Associations
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  # Validations
  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  # Associations
  has_many :bookmarks

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    # @movie = Movie.find(params[:movie_id])
    @bookmark.list = @list
    # @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render 'new'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    # From the form
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def index
    @lists = List.all
  end

  def show
    @movies = Movie.all
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.all
  end

  def destroy
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/application/_card.html.erb
<%# I will have to add the UI Kit card category and card grid later %>
<div class="card-category m-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('/images/netflix_and_chill.jpg') %>)">
  <div>
    <h1><%= list.name %></h1>
    <%= link_to "", list_path(list) %>
  </div>
</div>
<%# class: "btn btn-outline-success" %>

app/views/application/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name, label_html: { class: 'text-light ' } %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-success mt-3' %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render 'lists/show' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-frame-content">
      <div class="page-frame-header">
      </div>
      <div class="page-frame-body">
        <div class="container">
          <div class="row justify-content-center">
            <div class="text-light">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <div class="page-frame-footer">
      </div>
    </div>
  </body>
</html>

app/views/lists/_movies_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: 'btn btn-success my-3' %>
<% end %>

app/views/lists/index.html.erb
<h1>Movie WatchList Builder</h1>
<%= link_to 'New Watch List', new_list_path, class: 'btn btn-success my-3' %>
<div class="d-flex flex-wrap">
  <% @lists.each do |list| %>
    <%= render 'card', list: list %>
  <% end %>
</div>

app/views/lists/new.html.erb
<% if @list.errors.any? %>
  <% @restaurant.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
  <h1>Create a new movie watchlist</h1>
    <div class="col-6 d-flex justify-content-center">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%= link_to "Back home", lists_path, class: "btn btn-success my-3" %>
<div class="row justify-content-between">
  <div class="col" style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5))">
    <h3>Movies on this list</h3>
    <hr>
    <div class="row">
      <% @list.bookmarks.each do |bookmark| %>
        <p>Name: <%= bookmark.movie.title %></p>
        <p>Rating: <%= bookmark.movie.rating %></p>
        <p>Comments: <%= bookmark.comment %></p>
        <p><%= link_to 'Delete comment', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </div>
  </div>
  <div class="col">
    <h1>Add a new review</h1>
    <div class="col-6">
      <%= render 'movies_form' %>
    </div>
  </div>
</div>
<hr>